language: java
jdk:
  - oraclejdk7
branches:
  only:
  - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: ./gradlew clean resolveAllDependencies assemble
script: ./gradlew check
env:
  global:
  - TERM=dumb